# Generated by Django 4.1 on 2022-12-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=300, null=True)),
                ('symbol', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'dimension',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('utility_form', models.CharField(blank=True, max_length=30, null=True)),
                ('usable', models.BooleanField(blank=True, default=True, null=True)),
                ('num_of_subequipments', models.IntegerField(blank=True, null=True)),
                ('hasSpecial', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='PhysicalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity', models.CharField(max_length=300, null=True)),
                ('unity_math', models.CharField(max_length=300, null=True)),
                ('convert_factor', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.dimension')),
            ],
            options={
                'db_table': 'physical_unit',
            },
        ),
        migrations.CreateModel(
            name='SubEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('max_dimension', models.FloatField(null=True)),
                ('min_dimension', models.FloatField(null=True)),
                ('isSolid', models.BooleanField(blank=True, default=True, null=True)),
                ('materialTracker', models.IntegerField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
            ],
            options={
                'db_table': 'subequipment',
            },
        ),
        migrations.CreateModel(
            name='PurchasedFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k1', models.FloatField(null=True)),
                ('k2', models.FloatField(null=True)),
                ('k3', models.FloatField(null=True)),
                ('fixed_value', models.FloatField(null=True)),
                ('fbm', models.FloatField(blank=True, null=True)),
                ('reference_year', models.IntegerField(blank=True, null=True)),
                ('is_reference', models.BooleanField(blank=True, default=0)),
                ('reference_material_id', models.IntegerField(blank=True, default=0)),
                ('cepci', models.FloatField(blank=True, null=True)),
                ('subequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.subequipment')),
            ],
            options={
                'db_table': 'purchase_factor',
            },
        ),
        migrations.CreateModel(
            name='PressureFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.FloatField(null=True)),
                ('c2', models.FloatField(null=True)),
                ('c3', models.FloatField(null=True)),
                ('pressure_min', models.FloatField(null=True)),
                ('pressure_max', models.FloatField(null=True)),
                ('condition', models.CharField(max_length=300, null=True)),
                ('subequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.subequipment')),
                ('unityReference', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='equipments.physicalunit')),
            ],
            options={
                'db_table': 'pressure_factor',
            },
        ),
        migrations.CreateModel(
            name='MaterialFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.FloatField(null=True)),
                ('b2', models.FloatField(null=True)),
                ('fm', models.FloatField(null=True)),
                ('condition', models.CharField(blank=True, max_length=300, null=True)),
                ('subequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.subequipment')),
            ],
            options={
                'db_table': 'material_factor',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.physicalunit'),
        ),
        migrations.CreateModel(
            name='CostMethodsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbm', models.BooleanField(null=True)),
                ('fpressure', models.BooleanField(null=True)),
                ('material_correction', models.BooleanField(null=True)),
                ('specialMethod', models.BooleanField(null=True)),
                ('material_field_name', models.CharField(max_length=100, null=True)),
                ('pressure_field_name', models.CharField(max_length=100, null=True)),
                ('special_function_name', models.CharField(max_length=100, null=True)),
                ('subequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.subequipment')),
            ],
            options={
                'db_table': 'cost_factors_guide',
            },
        ),
        migrations.CreateModel(
            name='ComplementConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant', models.CharField(max_length=300, null=True)),
                ('value', models.FloatField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('subequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.subequipment')),
            ],
            options={
                'db_table': 'equipment_complement_constants',
            },
        ),
    ]
