# Generated by Django 4.1 on 2022-12-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subequipment',
            name='materialTracker',
        ),
    ]
