# Generated by Django 4.1 on 2022-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.AddField(
            model_name='equipment',
            name='reference_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
