# Generated by Django 4.1 on 2022-08-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_remove_equipment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='reference_year',
            new_name='num_of_subequipments',
        ),
    ]
