# Generated by Django 4.1 on 2022-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_rename_reference_year_equipment_num_of_subequipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedfactor',
            name='fbm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
