# Generated by Django 4.1 on 2023-01-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_alter_equipment_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='subequipment',
            name='default_physical_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipments.physicalunit'),
        ),
    ]
