# Generated by Django 4.1 on 2022-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_purchasedfactor_fbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedfactor',
            name='reference_material_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
