# Generated by Django 4.1 on 2022-08-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_purchasedfactor_reference_material_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BareModuleCostFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbm', models.BooleanField(null=True)),
                ('fpressure', models.BooleanField(null=True)),
                ('material_correction', models.BooleanField(null=True)),
                ('specialMethod', models.BooleanField(null=True)),
                ('subequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.subequipment')),
            ],
            options={
                'db_table': 'baremodule_cost_factor',
            },
        ),
        migrations.DeleteModel(
            name='BareModule',
        ),
    ]
