# Generated by Django 4.1 on 2022-08-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_baremodulecostfactor_delete_baremodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='baremodulecostfactor',
            name='material_field_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baremodulecostfactor',
            name='pressure_field_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
