# Generated by Django 4.1 on 2022-08-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_baremodulecostfactor_material_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurefactor',
            name='subequipment',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='equipments.physicalunit'),
        ),
    ]
