# Generated by Django 4.1 on 2022-08-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_pressurefactor_unityreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurefactor',
            name='unityReference',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='equipments.physicalunit'),
        ),
        migrations.CreateModel(
            name='CostMethodsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbm', models.BooleanField(null=True)),
                ('fpressure', models.BooleanField(null=True)),
                ('material_correction', models.BooleanField(null=True)),
                ('specialMethod', models.BooleanField(null=True)),
                ('material_field_name', models.CharField(max_length=100, null=True)),
                ('pressure_field_name', models.CharField(max_length=100, null=True)),
                ('subequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.subequipment')),
            ],
            options={
                'db_table': 'cost_factors_guide',
            },
        ),
    ]
