# Generated by Django 4.1 on 2022-08-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_alter_pressurefactor_unityreference_costmethodsguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BareModuleCostFactor',
        ),
    ]
