# Generated by Django 4.1 on 2022-08-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_costmethodsguide_special_function_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='active',
            new_name='usable',
        ),
    ]
